### ISSUE TITLE
start_astron_cluster.bat doesn't recognize "astrond" as command

### ISSUE THREAD

**Issue by crimsonKss** [toontown-classic/toontown-otp-ai#1]
i presume it's a file needed to be there? i don't know exactly, but i've seen something about a "astrond.exe" if that's the case, it's not on the folder the batch file is looking for

**Comment by cmarshall108** [comment]
@RaphaP3 Since this repo was originally forked from the Toontown Infinite project, this was left here which runs the Astron project used by Toontown Infinite. This is completely irrelevant to this project and is not used here.

**Comment by crimsonKss** [comment]
so i don't need the toontown-otp-ai to run the server?

**Comment by cmarshall108** [comment]
@RaphaP3 You do need this repository to run the 2003 Toontown game server cluster, this repository is for the game specific logic and the toontown-otp repository is for the game management specific stuff.

**Comment by crimsonKss** [comment]
have you thought of doing a tutorial? like, on the README or something, i'm not a developer, i'm just a guy that wants to see and play Toontown 2003.
